image: samueldebruyn/debian-git

pipelines:

  branches:
    master: 
      - step:
          script:
            - apt-get update
            - echo "Y" | apt-get install curl git-ftp
            - curl icanhazip.com
            - git ftp push --user $FTP_USERNAME --passwd $FTP_PASSWORD $FTP_PROTOCOL://$FTP_HOST$FTP_FOLDER